### ISSUE TITLE
Config view

### ISSUE THREAD

**Issue by azubieta** [plasma-light/plasma-widget-radio#4]
@UriHerrera Need a mockup of the Configuration view, with the play list edition tools.

**Comment by UriHerrera** [comment]
Alright I'm doing it.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/e4W8Hhd.png)

The Up and Down buttons could be just text too but I used an icon. The labels would be: _Move up_ and _Move down_.

**Comment by azubieta** [comment]
@UriHerrera give it a try to the new settings view at the development branch.

Note: Metadata fetching from radio stations is still missing.

**Comment by UriHerrera** [comment]
@azubieta It's failing to compile:

```
/home/uri/compile/plasma-widget-radio/plugin/radioplayer.cpp: En la función miembro ‘void RadioPlayer::createCoreConnections()’:
/home/uri/compile/plasma-widget-radio/plugin/radioplayer.cpp:70:89: error: ‘libvlc_media_list_player_get_media_player’ no se declaró en este ámbito
libvlc_media_player_t * mp = libvlc_media_list_player_get_media_player(_mediaListPlayer);
```

El error se repite en otras lineas con 

```
libvlc_media_player_t * mp = libvlc_media_list_player_get_media_player(_mediaListPlayer);
libvlc_media_player_t *player = libvlc_media_list_player_get_media_player(_mediaListPlayer);
```

# 

Got it working. I needed version 3.0.0 which is currently the daily git builds. This is because `libvlc_media_list_player_get_media_player` is not avialable in version 2.2.0, 2.2.3 and 2.2.4.

Here's the plasmoid working:
![](http://i.imgur.com/YqcpmyH.png)

I tested it adding 2 stations. One is a URL pointing to an mp3 file and the other is just the IP address.
